### ISSUE TITLE
Question about the License

### ISSUE THREAD

**Issue by fredo-dedup** [RiemannAI/openRT#1]
Hello there,
I had the project of porting your library to Julia, but it occurred to me midway that the AGPL license is "strong copyleft" which means that I will have to use the same license for my port since a translation to another language is a derived work (if I understood correctly what I read about AGPL). My initial choice was to use a more flexible license such as MIT but this seems impossible now.
Is there any chance that you could change your license to another one with no copyleft ?
I understand that you may have constraints or preferences for your license choice, which is totally ok. I just thought that I should ask.
Thanks.

**Comment by Dan-RAI** [comment]
Hello,

thanks for your interest in openRT. 

Indeed, AGPL is strong copyleft, and that’s why we picked it. In case your project is not compatible with this licence, we suggest to take a look if the Riemann-Theta implementation of the [abelfunctions](https://github.com/abelfunctions/abelfunctions) package, with MIT licence, is sufficient for your needs. OpenRT is based on the abelfunctions package and the improvements we made are mainly of relevance for our [theta](https://github.com/RiemannAI/theta) library.
